# Configuration Jekyll pour le site de cartographie
title: "Mes lieux"
description: "Cartographie de mes lieux visités"
baseurl: ""
url: "http://localhost:4000"

# Collections
collections:
  places:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown
markdown: kramdown
highlighter: rouge

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git/
  - .gitignore
  - setup-site.sh

# Defaults
defaults:
  - scope:
      path: ""
      type: "places"
    values:
      layout: "place"
